apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sup-platform.fullname" . }}-secret
  labels:
    {{- include "sup-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  CARD_ENCRYPT_KEY: {{ .Values.secrets.cardEncryptKey | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
